#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Console\Application;
use Palladiumlab\Console\Commands;

define('NO_AGENT_CHECK', true);
define('NOT_CHECK_PERMISSIONS', true);
define('PERFMON_STOP', true);
define('ROOT_PATH', dirname(__DIR__));
define('LOG_PATH', ROOT_PATH . '/logs');
define('CONSOLE_APPLICATION', true);

set_time_limit(0);

$_SERVER["DOCUMENT_ROOT"] = ROOT_PATH;

require $_SERVER["DOCUMENT_ROOT"] . "/bitrix/modules/main/include/prolog_before.php";

$app = new Application('palladiumlab');

$app->addCommands([
	new Commands\Deploy\ConstantsCommand(),
	new Commands\Cache\Clear(),
]);

$app->run();
