<li><img src="/local/templates/main/assets/img/payment-logo-1.svg" alt=""></li>
<li><img src="/local/templates/main/assets/img/payment-logo-2.svg" alt=""></li>
<li><img src="/local/templates/main/assets/img/payment-logo-3.svg" alt=""></li>
<li><img src="/local/templates/main/assets/img/payment-logo-4.svg" alt=""></li>
<li><img src="/local/templates/main/assets/img/payment-logo-5.svg" alt=""></li>
<li><img src="/local/templates/main/assets/img/payment-logo-6.svg" alt=""></li>
<li><img src="/local/templates/main/assets/img/payment-logo-7.svg" alt=""></li>
<li><img src="/local/templates/main/assets/img/payment-logo-8.svg" alt=""></li>
<li><img src="/local/templates/main/assets/img/payment-logo-9.svg" alt=""></li>